Update cfdeploy.yml

diff --git a/.github/workflows/cfdeploy.yml b/.github/workflows/cfdeploy.yml
--- a/.github/workflows/cfdeploy.yml
+++ b/.github/workflows/cfdeploy.yml
@@ -1,15 +1,22 @@
-name: Deploy
+name: Choose and Deploy
 
 on:
   workflow_dispatch:
     inputs:
+      workflow_choice:
+        description: 'Select the workflow to run'
+        required: true
+        type: choice
+        options:
+          - Deploy
+          - Snapshot Deploy
       cf_space:
         description: 'Specify the Cloud Foundry space to deploy to'
         required: true
         default: 'developcap'
       deploy_branch:
-        description: 'Specify the branch to deploy from'
-        required: true
+        description: 'Specify the branch to deploy from (only for Deploy workflow)'
+        required: false
       repository_id:
         description: 'Specify the Repository ID (leave blank if deploying to developcap)'
         required: false
@@ -21,6 +28,7 @@ permissions:
 jobs:
   Deploy:
     runs-on: ubuntu-latest
+    if: ${{ github.event.inputs.workflow_choice == 'Deploy' }}
 
     steps:
       - name: Checkout repository
@@ -37,7 +45,6 @@ jobs:
       - name: Build and package
         run: |
           mvn clean install -P unit-tests  -DskipIntegrationTests
-          
 
       - name: Verify and Checkout Deploy Branch
         run: |
@@ -65,27 +72,6 @@ jobs:
             fi
           fi
 
-      # - name: Set REPOSITORY_ID
-      #   id: set_repository_id
-      #   run: |
-      #     if [ "${{ github.event.inputs.cf_space }}" = "developcap" ]; then
-      #       echo "Using REPOSITORY_ID from secrets"
-      #       echo "::set-output name=repository_id::${{ secrets.REPOSITORY_ID }}"
-      #     else
-      #       if [ -z "${{ github.event.inputs.repository_id }}" ]; then
-      #         echo "REPOSITORY_ID must be provided for non-developcap spaces"
-      #         exit 1
-      #       else
-      #         echo "Using provided REPOSITORY_ID"
-      #         echo "::set-output name=repository_id::${{ github.event.inputs.repository_id }}"
-      #       fi
-      #     fi
-
-      # - name: Consume GitHub Packages (com.sap.cds.sdm-root and com.sap.cds.sdm)
-      #   run: |
-      #     mvn dependency:get -Dartifact=com.sap.cds:sdm-root:LATEST -DrepoUrl=https://maven.pkg.github.com/cap-java/sdm
-      #     mvn dependency:get -Dartifact=com.sap.cds:sdm:LATEST -DrepoUrl=https://maven.pkg.github.com/cap-java/sdm
-
       - name: Prepare and Deploy to Cloud Foundry
         run: |
           echo "Current Branch......"
@@ -100,30 +86,122 @@ jobs:
           cd ..
           echo "changed to demoapp directory"
           pwd
-          
-          # Replace placeholder with actual REPOSITORY_ID value
+
           sed -i 's|__REPOSITORY_ID__|'${{ steps.set_repository_id.outputs.repository_id }}'|g' ./mta.yaml
-          
+
           wget -P /tmp https://github.com/SAP/cloud-mta-build-tool/releases/download/v1.2.28/cloud-mta-build-tool_1.2.28_Linux_amd64.tar.gz
           tar -xvzf /tmp/cloud-mta-build-tool_1.2.28_Linux_amd64.tar.gz
           sudo mv mbt /usr/local/bin/
 
           mbt build
-          
-          # Install cf & login 
-          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key \
-          | sudo tee /etc/apt/trusted.gpg.d/cloudfoundry.asc
-          echo "deb https://packages.cloudfoundry.org/debian stable main" \
-          | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
+
+          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo tee /etc/apt/trusted.gpg.d/cloudfoundry.asc
+          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
           sudo apt update
           sudo apt install cf-cli
-          
-          # Install cf CLI plugin
+
           cf install-plugin multiapps -f
 
-          # Login to Cloud Foundry again to ensure session is active
           cf login -a ${{ secrets.CF_API }} -u ${{ secrets.CF_USER }} -p ${{ secrets.CF_PASSWORD }} -o ${{ secrets.CF_ORG }} -s ${{ github.event.inputs.cf_space }}
 
-          # Deploy the application
+          echo "Running cf deploy"
+          cf deploy mta_archives/demoappjava_1.0.0.mtar -f
+
+  SnapshotDeploy:
+    runs-on: ubuntu-latest
+    if: ${{ github.event.inputs.workflow_choice == 'Snapshot Deploy' }}
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+        with:
+          ref: develop
+
+      - name: Set up Java 17
+        uses: actions/setup-java@v3
+        with:
+          java-version: 17
+          distribution: 'temurin'
+
+      - name: Verify and Checkout Deploy Branch
+        run: |
+          git fetch origin
+          if git rev-parse --verify origin/develop_deploy; then
+            git checkout develop_deploy
+          else
+            echo "Branch 'develop_deploy' not found. Please verify the branch name."
+            exit 1
+          fi
+
+      - name: Deleting the sdm directory for fresh build
+        run: |
+          pwd
+          cd
+          rm -rf .m2/repository/com/sap/cds
+
+      - name: Set REPOSITORY_ID
+        id: set_repository_id
+        run: |
+          if [ "${{ github.event.inputs.cf_space }}" = "developcap" ]; then
+            echo "Using REPOSITORY_ID from secrets"
+            echo "::set-output name=repository_id::${{ secrets.REPOSITORY_ID }}"
+          else
+            if [ -z "${{ github.event.inputs.repository_id }}" ]; then
+              echo "REPOSITORY_ID must be provided for non-developcap spaces"
+              exit 1
+            else
+              echo "Using provided REPOSITORY_ID"
+              echo "::set-output name=repository_id::${{ github.event.inputs.repository_id }}"
+            fi
+          fi
+
+      - name: Configure Maven for GitHub Packages
+        run: |
+          mkdir -p ~/.m2
+          cat > ~/.m2/settings.xml <<EOF
+          <settings>
+            <servers>
+              <server>
+                <id>github-snapshot</id>
+                <username>${{ github.actor }}</username>
+                <password>${{ secrets.GITHUB_TOKEN }}</password>
+              </server>
+            </servers>
+          </settings>
+          EOF
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Prepare and Deploy to Cloud Foundry
+        run: |
+          echo "Current Branch......"
+          git branch
+          pwd
+          cd /home/runner/work/sdm/sdm/cap-notebook/demoapp
+
+          cd app
+          rm -rf node_modules package-lock.json
+
+          npm i
+
+          cd ..
+
+          sed -i 's|__REPOSITORY_ID__|'${{ steps.set_repository_id.outputs.repository_id }}'|g' ./mta.yaml
+
+          wget -P /tmp https://github.com/SAP/cloud-mta-build-tool/releases/download/v1.2.28/cloud-mta-build-tool_1.2.28_Linux_amd64.tar.gz
+          tar -xvzf /tmp/cloud-mta-build-tool_1.2.28_Linux_amd64.tar.gz
+          sudo mv mbt /usr/local/bin/
+
+          mbt build
+
+          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo tee /etc/apt/trusted.gpg.d/cloudfoundry.asc
+          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
+          sudo apt update
+          sudo apt install cf-cli
+
+          cf install-plugin multiapps -f
+
+          cf login -a ${{ secrets.CF_API }} -u ${{ secrets.CF_USER }} -p ${{ secrets.CF_PASSWORD }} -o ${{ secrets.CF_ORG }} -s ${{ github.event.inputs.cf_space }}
+
           echo "Running cf deploy"
           cf deploy mta_archives/demoappjava_1.0.0.mtar -f
