Update cfdeploy.yml

diff --git a/.github/workflows/cfdeploy.yml b/.github/workflows/cfdeploy.yml
--- a/.github/workflows/cfdeploy.yml
+++ b/.github/workflows/cfdeploy.yml
@@ -1,10 +1,17 @@
 name: Deploy
 
 on:
+  push:
+    branches:
+      - cf-deploy-spaces
   workflow_dispatch:
     inputs:
       cf_space:
         description: 'Specify the Cloud Foundry space to deploy to'
+        required: true
+        default: 'developcap'
+      deploy_branch:
+        description: 'Specify the branch to deploy from'
         required: true
       repository_id:
         description: 'Specify the Repository ID (leave blank if deploying to developcap)'
@@ -22,7 +29,7 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v2
         with:
-          ref: develop
+          ref: ${{ github.event.inputs.deploy_branch }}
 
       - name: Set up Java 17
         uses: actions/setup-java@v3
@@ -33,51 +40,29 @@ jobs:
       - name: Verify and Checkout Deploy Branch
         run: |
           git fetch origin
-          if git rev-parse --verify origin/develop_deploy; then
-            git checkout develop_deploy
+          if git rev-parse --verify origin/local_deploy; then
+            git checkout local_deploy
           else
-            echo "Branch 'develop_deploy' not found. Please verify the branch name."
+            echo "Branch 'local_deploy' not found. Please verify the branch name."
             exit 1
           fi
 
-      - name: Deleting the sdm directory for fresh build
-        run: |
-          pwd
-          cd
-          rm -rf .m2/repository/com/sap/cds
+      # - name: Set REPOSITORY_ID
+      #   id: set_repository_id
+      #   run: |
+      #     if [ "${{ github.event.inputs.cf_space }}" = "developcap" ]; then
+      #       echo "Using REPOSITORY_ID from secrets"
+      #       echo "::set-output name=repository_id::${{ secrets.REPOSITORY_ID }}"
+      #     else
+      #       if [ -z "${{ github.event.inputs.repository_id }}" ]; then
+      #         echo "REPOSITORY_ID must be provided for non-developcap spaces"
+      #         exit 1
+      #       else
+      #         echo "Using provided REPOSITORY_ID"
+      #         echo "::set-output name=repository_id::${{ github.event.inputs.repository_id }}"
+      #       fi
+      #     fi
 
-      - name: Set REPOSITORY_ID
-        id: set_repository_id
-        run: |
-          if [ "${{ github.event.inputs.cf_space }}" = "developcap" ]; then
-            echo "Using REPOSITORY_ID from secrets"
-            echo "::set-output name=repository_id::${{ secrets.REPOSITORY_ID }}"
-          else
-            if [ -z "${{ github.event.inputs.repository_id }}" ]; then
-              echo "REPOSITORY_ID must be provided for non-developcap spaces"
-              exit 1
-            else
-              echo "Using provided REPOSITORY_ID"
-              echo "::set-output name=repository_id::${{ github.event.inputs.repository_id }}"
-            fi
-          fi
-
-      - name: Configure Maven for GitHub Packages
-        run: |
-          mkdir -p ~/.m2
-          cat > ~/.m2/settings.xml <<EOF
-          <settings>
-            <servers>
-              <server>
-                <id>github-snapshot</id>
-                <username>${{ github.actor }}</username>
-                <password>${{ secrets.GITHUB_TOKEN }}</password>
-              </server>
-            </servers>
-          </settings>
-          EOF
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       # - name: Consume GitHub Packages (com.sap.cds.sdm-root and com.sap.cds.sdm)
       #   run: |
       #     mvn dependency:get -Dartifact=com.sap.cds:sdm-root:LATEST -DrepoUrl=https://maven.pkg.github.com/cap-java/sdm
@@ -97,7 +82,11 @@ jobs:
           tar -xvzf /tmp/cloud-mta-build-tool_1.2.28_Linux_amd64.tar.gz
           sudo mv mbt /usr/local/bin/
 
-          mbt build
+
+          # Build the MTA project
+          echo "Running mbt build"
+          mbt build -p=cf -t mta_archives --mtar demoappjava-1.0.0.mtar
+
           
           # Install cf & login 
           wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key \
@@ -111,8 +100,13 @@ jobs:
           cf install-plugin multiapps -f
 
           # Login to Cloud Foundry again to ensure session is active
+
           cf login -a ${{ secrets.CF_API }} -u ${{ secrets.CF_USER }} -p ${{ secrets.CF_PASSWORD }} -o ${{ secrets.CF_ORG }} -s ${{ github.event.inputs.cf_space }}
 
           # Deploy the application
+          pwd
+          ls -lart
+          # cd mta_archives
+          # ls -lart
           echo "Running cf deploy"
-          cf deploy mta_archives/demoappjava_1.0.0.mtar -f
+          cf deploy /home/runner/work/sdm/sdm/cap-notebook/demoapp/mta_archives/demoappjava-1.0.0.mtar -f
