Update cfdeploy.yml

diff --git a/.github/workflows/cfdeploy.yml b/.github/workflows/cfdeploy.yml
--- a/.github/workflows/cfdeploy.yml
+++ b/.github/workflows/cfdeploy.yml
@@ -25,25 +25,17 @@ jobs:
         with:
           java-version: 17
           distribution: 'temurin'
-
-      - name: Login to Cloud Foundry
+          
+      - name: Verify and Checkout Deploy Branch
         run: |
-          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
-          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
-          sudo apt-get update
-          sudo apt-get install cf8-cli
-          cf login -a ${{ secrets.CF_API }} -u ${{ secrets.CF_USER }} -p ${{ secrets.CF_PASSWORD }} -o ${{ secrets.CF_ORG }} -s ${{ secrets.CF_SPACE }}
-
-      - name: Build and package
-        run: |
-          cd sdm
-          pwd
-          echo "Listing the content before build"
-          ls -lart
-          mvn clean install
-          echo "Listing the content after build"
-          ls -lart
-
+          git fetch origin
+          if git show-ref --verify --quiet refs/heads/deploy; then
+            git checkout deploy
+          else
+            echo "Branch 'deploy' not found. Please verify the branch name."
+            exit 1
+          fi
+          
       - name: Prepare and Deploy to Cloud Foundry
         run: |
           git checkout deploy
