Update cfdeploy.yml

diff --git a/.github/workflows/cfdeploy.yml b/.github/workflows/cfdeploy.yml
--- a/.github/workflows/cfdeploy.yml
+++ b/.github/workflows/cfdeploy.yml
@@ -10,118 +10,129 @@ jobs:
     runs-on: ubuntu-latest
     
     steps:
-    # Step 1: Checkout the repository
-    - name: Checkout the repository
-      uses: actions/checkout@v2
-      with:
-        repository: 'cap-java/sdm'
-    
-    # Step 2: Switch to 'develop_deploy' branch
-    - name: Checkout develop_deploy branch
-      run: git checkout develop_deploy
+      - name: Checkout repository
+        uses: actions/checkout@v2
+        with:
+          ref: develop
 
-    # Step 3: Update settings.xml
-    - name: Update settings.xml
-      run: |
-        echo '<?xml version="1.0" encoding="UTF-8"?>' > settings.xml
-        echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">' >> settings.xml
-        echo '   <profiles>' >> settings.xml
-        echo '      <profile>' >> settings.xml
-        echo '         <id>release.build</id>' >> settings.xml
-        echo '         <pluginRepositories>' >> settings.xml
-        echo '            <pluginRepository>' >> settings.xml
-        echo '               <id>artifactory</id>' >> settings.xml
-        echo '               <url>https://int.repositories.cloud.sap/artifactory/build-releases/</url>' >> settings.xml
-        echo '            </pluginRepository>' >> settings.xml
-        echo '         </pluginRepositories>' >> settings.xml
-        echo '         <repositories>' >> settings.xml
-        echo '            <repository>' >> settings.xml
-        echo '               <id>artifactory</id>' >> settings.xml
-        echo '               <url>https://int.repositories.cloud.sap/artifactory/build-releases/</url>' >> settings.xml
-        echo '            </repository>' >> settings.xml
-        echo '         </repositories>' >> settings.xml
-        echo '         <properties>' >> settings.xml
-        echo '            <tycho.disableP2Mirrors>true</tycho.disableP2Mirrors>' >> settings.xml
-        echo '            <tycho.localArtifacts>ignore</tycho.localArtifacts>' >> settings.xml
-        echo '         </properties>' >> settings.xml
-        echo '      </profile>' >> settings.xml
-        echo '      <profile>' >> settings.xml
-        echo '         <id>milestone.build</id>' >> settings.xml
-        echo '         <pluginRepositories>' >> settings.xml
-        echo '            <pluginRepository>' >> settings.xml
-        echo '               <id>artifactory</id>' >> settings.xml
-        echo '               <url>https://int.repositories.cloud.sap/artifactory/build-milestones/</url>' >> settings.xml
-        echo '            </pluginRepository>' >> settings.xml
-        echo '         </pluginRepositories>' >> settings.xml
-        echo '         <repositories>' >> settings.xml
-        echo '            <repository>' >> settings.xml
-        echo '               <id>artifactory</id>' >> settings.xml
-        echo '               <url>https://int.repositories.cloud.sap/artifactory/build-milestones/</url>' >> settings.xml
-        echo '            </repository>' >> settings.xml
-        echo '         </repositories>' >> settings.xml
-        echo '         <properties>' >> settings.xml
-        echo '            <tycho.disableP2Mirrors>true</tycho.disableP2Mirrors>' >> settings.xml
-        echo '            <tycho.localArtifacts>ignore</tycho.localArtifacts>' >> settings.xml
-        echo '         </properties>' >> settings.xml
-        echo '      </profile>' >> settings.xml
-        echo '      <profile>' >> settings.xml
-        echo '         <id>snapshot.build</id>' >> settings.xml
-        echo '         <pluginRepositories>' >> settings.xml
-        echo '            <pluginRepository>' >> settings.xml
-        echo '               <id>artifactory</id>' >> settings.xml
-        echo '               <url>https://int.repositories.cloud.sap/artifactory/build-snapshots/</url>' >> settings.xml
-        echo '            </pluginRepository>' >> settings.xml
-        echo '         </pluginRepositories>' >> settings.xml
-        echo '         <repositories>' >> settings.xml
-        echo '            <repository>' >> settings.xml
-        echo '               <id>cap-java</id>' >> settings.xml
-        echo '               <url>https://int.repositories.cloud.sap/artifactory/proxy-cap-java/</url>' >> settings.xml
-        echo '            </repository>' >> settings.xml
-        echo '            <repository>' >> settings.xml
-        echo '               <id>artifactory</id>' >> settings.xml
-        echo '               <url>https://int.repositories.cloud.sap/artifactory/build-snapshots/</url>' >> settings.xml
-        echo '            </repository>' >> settings.xml
-        echo '            <repository>' >> settings.xml
-        echo '               <id>cap-sdm-java</id>' >> settings.xml
-        echo '               <url>https://int.repositories.cloud.sap/artifactory/proxy-cap-sdm-java/</url>' >> settings.xml
-        echo '            </repository>' >> settings.xml
-        echo '         </repositories>' >> settings.xml
-        echo '         <properties>' >> settings.xml
-        echo '            <tycho.disableP2Mirrors>true</tycho.disableP2Mirrors>' >> settings.xml
-        echo '            <tycho.localArtifacts>ignore</tycho.localArtifacts>' >> settings.xml
-        echo '         </properties>' >> settings.xml
-        echo '      </profile>' >> settings.xml
-        echo '      <profile>' >> settings.xml
-        echo '         <id>sonar</id>' >> settings.xml
-        echo '         <activation>' >> settings.xml
-        echo '            <activeByDefault>true</activeByDefault>' >> settings.xml
-        echo '         </activation>' >> settings.xml
-        echo '         <properties>' >> settings.xml
-        echo '            <sonar.host.url>https://sonar.tools.sap</sonar.host.url>' >> settings.xml
-        echo '            <tycho.disableP2Mirrors>true</tycho.disableP2Mirrors>' >> settings.xml
-        echo '            <tycho.localArtifacts>ignore</tycho.localArtifacts>' >> settings.xml
-        echo '         </properties>' >> settings.xml
-        echo '      </profile>' >> settings.xml
-        echo '   </profiles>' >> settings.xml
-        echo '   <activeProfiles>' >> settings.xml
-        echo '      <activeProfile>snapshot.build</activeProfile>' >> settings.xml
-        echo '   </activeProfiles>' >> settings.xml
-        echo '   <pluginGroups>' >> settings.xml
-        echo '      <pluginGroup>com.sap.ldi</pluginGroup>' >> settings.xml
-        echo '   </pluginGroups>' >> settings.xml
-        echo '   <servers>' >> settings.xml
-        echo '      <server>' >> settings.xml
-        echo '         <id>artifactory</id>' >> settings.xml
-        echo '         <username>${env.SERVER_USER}</username>' >> settings.xml
-        echo '         <password>${env.SERVER_PASSWORD}</password>' >> settings.xml
-        echo '      </server>' >> settings.xml
-        echo '   </servers>' >> settings.xml
-        echo '</settings>' >> settings.xml
+      - name: Set up Java 17
+        uses: actions/setup-java@v3
+        with:
+          java-version: 17
+          distribution: 'temurin'
+          
 
-    # Step 4: Change directory to cap-notebook/demoapp
-    - name: Change directory to cap-notebook/demoapp
-      run: cd cap-notebook/demoapp
+      # Step 3: Update settings.xml
+      - name: Update settings.xml
+        run: |
+          echo '<?xml version="1.0" encoding="UTF-8"?>' > settings.xml
+          echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">' >> settings.xml
+          echo '   <profiles>' >> settings.xml
+          echo '      <profile>' >> settings.xml
+          echo '         <id>release.build</id>' >> settings.xml
+          echo '         <pluginRepositories>' >> settings.xml
+          echo '            <pluginRepository>' >> settings.xml
+          echo '               <id>artifactory</id>' >> settings.xml
+          echo '               <url>https://int.repositories.cloud.sap/artifactory/build-releases/</url>' >> settings.xml
+          echo '            </pluginRepository>' >> settings.xml
+          echo '         </pluginRepositories>' >> settings.xml
+          echo '         <repositories>' >> settings.xml
+          echo '            <repository>' >> settings.xml
+          echo '               <id>artifactory</id>' >> settings.xml
+          echo '               <url>https://int.repositories.cloud.sap/artifactory/build-releases/</url>' >> settings.xml
+          echo '            </repository>' >> settings.xml
+          echo '         </repositories>' >> settings.xml
+          echo '         <properties>' >> settings.xml
+          echo '            <tycho.disableP2Mirrors>true</tycho.disableP2Mirrors>' >> settings.xml
+          echo '            <tycho.localArtifacts>ignore</tycho.localArtifacts>' >> settings.xml
+          echo '         </properties>' >> settings.xml
+          echo '      </profile>' >> settings.xml
+          echo '      <profile>' >> settings.xml
+          echo '         <id>milestone.build</id>' >> settings.xml
+          echo '         <pluginRepositories>' >> settings.xml
+          echo '            <pluginRepository>' >> settings.xml
+          echo '               <id>artifactory</id>' >> settings.xml
+          echo '               <url>https://int.repositories.cloud.sap/artifactory/build-milestones/</url>' >> settings.xml
+          echo '            </pluginRepository>' >> settings.xml
+          echo '         </pluginRepositories>' >> settings.xml
+          echo '         <repositories>' >> settings.xml
+          echo '            <repository>' >> settings.xml
+          echo '               <id>artifactory</id>' >> settings.xml
+          echo '               <url>https://int.repositories.cloud.sap/artifactory/build-milestones/</url>' >> settings.xml
+          echo '            </repository>' >> settings.xml
+          echo '         </repositories>' >> settings.xml
+          echo '         <properties>' >> settings.xml
+          echo '            <tycho.disableP2Mirrors>true</tycho.disableP2Mirrors>' >> settings.xml
+          echo '            <tycho.localArtifacts>ignore</tycho.localArtifacts>' >> settings.xml
+          echo '         </properties>' >> settings.xml
+          echo '      </profile>' >> settings.xml
+          echo '      <profile>' >> settings.xml
+          echo '         <id>snapshot.build</id>' >> settings.xml
+          echo '         <pluginRepositories>' >> settings.xml
+          echo '            <pluginRepository>' >> settings.xml
+          echo '               <id>artifactory</id>' >> settings.xml
+          echo '               <url>https://int.repositories.cloud.sap/artifactory/build-snapshots/</url>' >> settings.xml
+          echo '            </pluginRepository>' >> settings.xml
+          echo '         </pluginRepositories>' >> settings.xml
+          echo '         <repositories>' >> settings.xml
+          echo '            <repository>' >> settings.xml
+          echo '               <id>cap-java</id>' >> settings.xml
+          echo '               <url>https://int.repositories.cloud.sap/artifactory/proxy-cap-java/</url>' >> settings.xml
+          echo '            </repository>' >> settings.xml
+          echo '            <repository>' >> settings.xml
+          echo '               <id>artifactory</id>' >> settings.xml
+          echo '               <url>https://int.repositories.cloud.sap/artifactory/build-snapshots/</url>' >> settings.xml
+          echo '            </repository>' >> settings.xml
+          echo '            <repository>' >> settings.xml
+          echo '               <id>cap-sdm-java</id>' >> settings.xml
+          echo '               <url>https://int.repositories.cloud.sap/artifactory/proxy-cap-sdm-java/</url>' >> settings.xml
+          echo '            </repository>' >> settings.xml
+          echo '         </repositories>' >> settings.xml
+          echo '         <properties>' >> settings.xml
+          echo '            <tycho.disableP2Mirrors>true</tycho.disableP2Mirrors>' >> settings.xml
+          echo '            <tycho.localArtifacts>ignore</tycho.localArtifacts>' >> settings.xml
+          echo '         </properties>' >> settings.xml
+          echo '      </profile>' >> settings.xml
+          echo '      <profile>' >> settings.xml
+          echo '         <id>sonar</id>' >> settings.xml
+          echo '         <activation>' >> settings.xml
+          echo '            <activeByDefault>true</activeByDefault>' >> settings.xml
+          echo '         </activation>' >> settings.xml
+          echo '         <properties>' >> settings.xml
+          echo '            <sonar.host.url>https://sonar.tools.sap</sonar.host.url>' >> settings.xml
+          echo '            <tycho.disableP2Mirrors>true</tycho.disableP2Mirrors>' >> settings.xml
+          echo '            <tycho.localArtifacts>ignore</tycho.localArtifacts>' >> settings.xml
+          echo '         </properties>' >> settings.xml
+          echo '      </profile>' >> settings.xml
+          echo '   </profiles>' >> settings.xml
+          echo '   <activeProfiles>' >> settings.xml
+          echo '      <activeProfile>snapshot.build</activeProfile>' >> settings.xml
+          echo '   </activeProfiles>' >> settings.xml
+          echo '   <pluginGroups>' >> settings.xml
+          echo '      <pluginGroup>com.sap.ldi</pluginGroup>' >> settings.xml
+          echo '   </pluginGroups>' >> settings.xml
+          echo '   <servers>' >> settings.xml
+          echo '      <server>' >> settings.xml
+          echo '         <id>artifactory</id>' >> settings.xml
+          echo '         <username>${env.SERVER_USER}</username>' >> settings.xml
+          echo '         <password>${env.SERVER_PASSWORD}</password>' >> settings.xml
+          echo '      </server>' >> settings.xml
+          echo '   </servers>' >> settings.xml
+          echo '</settings>' >> settings.xml
 
-    # Step 5: Run the mbt build
-    - name: Run mbt build
-      run: mbt build
+      - name: Verify and Checkout Deploy Branch
+        run: |
+          git fetch origin
+          if git rev-parse --verify origin/develop_deploy; then
+            git checkout develop_deploy
+          else
+            echo "Branch 'develop_deploy' not found. Please verify the branch name."
+            exit 1
+          fi
+  
+      # Step 5: Run the mbt build
+      - name: Run mbt build
+        run: |
+          pwd
+          cd cap-notebook/demoapp
+          mbt build
