Update cfdeploy.yml

diff --git a/.github/workflows/cfdeploy.yml b/.github/workflows/cfdeploy.yml
--- a/.github/workflows/cfdeploy.yml
+++ b/.github/workflows/cfdeploy.yml
@@ -47,194 +47,196 @@ jobs:
           echo "🚀 Building and packaging..."
           mvn clean install -P unit-tests -DskipIntegrationTests
           echo "✅ Build and packaging completed successfully!"
+          echo "cds version is: "
+          cds v -i
+           
+  #     - name: Verify and Checkout Deploy Branch 🔄
+  #       run: |
+  #         git fetch origin
+  #         echo "📂 Verifying 'local_deploy' branch..."
+  #         if git rev-parse --verify origin/local_deploy; then
+  #           git checkout local_deploy
+  #           echo "✅ Branch checked out successfully!"
+  #         else
+  #           echo "❌ Branch 'local_deploy' not found. Please verify the branch name."
+  #           exit 1
+  #         fi
 
-      - name: Verify and Checkout Deploy Branch 🔄
-        run: |
-          git fetch origin
-          echo "📂 Verifying 'local_deploy' branch..."
-          if git rev-parse --verify origin/local_deploy; then
-            git checkout local_deploy
-            echo "✅ Branch checked out successfully!"
-          else
-            echo "❌ Branch 'local_deploy' not found. Please verify the branch name."
-            exit 1
-          fi
+  #     - name: Set REPOSITORY_ID 🔍
+  #       id: set_repository_id
+  #       run: |
+  #         echo "🔄 Setting Repository ID..."
+  #         if [ "${{ github.event.inputs.cf_space }}" = "developcap" ]; then
+  #           echo "Using REPOSITORY_ID from secrets"
+  #           echo "::set-output name=repository_id::${{ secrets.REPOSITORY_ID }}"
+  #         else
+  #           if [ -z "${{ github.event.inputs.repository_id }}" ]; then
+  #             echo "❌ REPOSITORY_ID must be provided for non-developcap spaces"
+  #             exit 1
+  #           else
+  #             echo "Using provided REPOSITORY_ID"
+  #             echo "::set-output name=repository_id::${{ github.event.inputs.repository_id }}"
+  #           fi
+  #         fi
 
-      - name: Set REPOSITORY_ID 🔍
-        id: set_repository_id
-        run: |
-          echo "🔄 Setting Repository ID..."
-          if [ "${{ github.event.inputs.cf_space }}" = "developcap" ]; then
-            echo "Using REPOSITORY_ID from secrets"
-            echo "::set-output name=repository_id::${{ secrets.REPOSITORY_ID }}"
-          else
-            if [ -z "${{ github.event.inputs.repository_id }}" ]; then
-              echo "❌ REPOSITORY_ID must be provided for non-developcap spaces"
-              exit 1
-            else
-              echo "Using provided REPOSITORY_ID"
-              echo "::set-output name=repository_id::${{ github.event.inputs.repository_id }}"
-            fi
-          fi
+  #     - name: Prepare and Deploy to Cloud Foundry ☁️
+  #       run: |
+  #         echo "🔄 Preparing to deploy..."
+  #         echo "Current Branch: 📂"
+  #         git branch
+  #         pwd
+  #         cd /home/runner/work/sdm/sdm/cap-notebook/demoapp/app
+  #         echo "Changed to app directory 📂"
+  #         pwd
 
-      - name: Prepare and Deploy to Cloud Foundry ☁️
-        run: |
-          echo "🔄 Preparing to deploy..."
-          echo "Current Branch: 📂"
-          git branch
-          pwd
-          cd /home/runner/work/sdm/sdm/cap-notebook/demoapp/app
-          echo "Changed to app directory 📂"
-          pwd
+  #         echo "🔄 Installing npm dependencies..."
+  #         npm i
 
-          echo "🔄 Installing npm dependencies..."
-          npm i
+  #         cd ..
+  #         echo "Changed to demoapp directory 📂"
+  #         pwd
 
-          cd ..
-          echo "Changed to demoapp directory 📂"
-          pwd
+  #         echo "🔧 Configuring mta.yaml..."
+  #         sed -i 's|__REPOSITORY_ID__|'${{ steps.set_repository_id.outputs.repository_id }}'|g' ./mta.yaml
 
-          echo "🔧 Configuring mta.yaml..."
-          sed -i 's|__REPOSITORY_ID__|'${{ steps.set_repository_id.outputs.repository_id }}'|g' ./mta.yaml
+  #         echo "📦 Downloading and setting up MBT..."
+  #         wget -P /tmp https://github.com/SAP/cloud-mta-build-tool/releases/download/v1.2.28/cloud-mta-build-tool_1.2.28_Linux_amd64.tar.gz
+  #         tar -xvzf /tmp/cloud-mta-build-tool_1.2.28_Linux_amd64.tar.gz
+  #         sudo mv mbt /usr/local/bin/
 
-          echo "📦 Downloading and setting up MBT..."
-          wget -P /tmp https://github.com/SAP/cloud-mta-build-tool/releases/download/v1.2.28/cloud-mta-build-tool_1.2.28_Linux_amd64.tar.gz
-          tar -xvzf /tmp/cloud-mta-build-tool_1.2.28_Linux_amd64.tar.gz
-          sudo mv mbt /usr/local/bin/
+  #         echo "🚀 Building with MBT..."
+  #         mbt build
+  #         echo "✅ Build completed!"
 
-          echo "🚀 Building with MBT..."
-          mbt build
-          echo "✅ Build completed!"
+  #         echo "🔧 Installing Cloud Foundry CLI..."
+  #         wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo tee /etc/apt/trusted.gpg.d/cloudfoundry.asc
+  #         echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
+  #         sudo apt update
+  #         sudo apt install cf-cli
 
-          echo "🔧 Installing Cloud Foundry CLI..."
-          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo tee /etc/apt/trusted.gpg.d/cloudfoundry.asc
-          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
-          sudo apt update
-          sudo apt install cf-cli
+  #         cf install-plugin multiapps -f
 
-          cf install-plugin multiapps -f
+  #         echo "🔑 Logging into Cloud Foundry..."
+  #         cf login -a ${{ secrets.CF_API }} -u ${{ secrets.CF_USER }} -p ${{ secrets.CF_PASSWORD }} -o ${{ secrets.CF_ORG }} -s ${{ github.event.inputs.cf_space }}
+  #         echo "✅ Logged in successfully!"
 
-          echo "🔑 Logging into Cloud Foundry..."
-          cf login -a ${{ secrets.CF_API }} -u ${{ secrets.CF_USER }} -p ${{ secrets.CF_PASSWORD }} -o ${{ secrets.CF_ORG }} -s ${{ github.event.inputs.cf_space }}
-          echo "✅ Logged in successfully!"
+  #         echo "🚀 Running cf deploy..."
+  #         cf deploy mta_archives/demoappjava_1.0.0.mtar -f
+  #         echo "✅ Deployment complete!"
 
-          echo "🚀 Running cf deploy..."
-          cf deploy mta_archives/demoappjava_1.0.0.mtar -f
-          echo "✅ Deployment complete!"
+  # SnapshotDeploy:
+  #   runs-on: ubuntu-latest
+  #   if: ${{ github.event.inputs.workflow_choice == 'Snapshot Deploy' }}
 
-  SnapshotDeploy:
-    runs-on: ubuntu-latest
-    if: ${{ github.event.inputs.workflow_choice == 'Snapshot Deploy' }}
+  #   steps:
+  #     - name: Checkout repository 📁
+  #       uses: actions/checkout@v2
+  #       with:
+  #         ref: develop
 
-    steps:
-      - name: Checkout repository 📁
-        uses: actions/checkout@v2
-        with:
-          ref: develop
+  #     - name: Set up Java 17 ☕
+  #       uses: actions/setup-java@v3
+  #       with:
+  #         java-version: 17
+  #         distribution: 'temurin'
 
-      - name: Set up Java 17 ☕
-        uses: actions/setup-java@v3
-        with:
-          java-version: 17
-          distribution: 'temurin'
+  #     - name: Verify and Checkout Deploy Branch 🔄
+  #       run: |
+  #         git fetch origin
+  #         echo "📂 Verifying 'develop_deploy' branch..."
+  #         if git rev-parse --verify origin/develop_deploy; then
+  #           git checkout develop_deploy
+  #           echo "✅ Branch checked out successfully!"
+  #         else
+  #           echo "❌ Branch 'develop_deploy' not found. Please verify the branch name."
+  #           exit 1
+  #         fi
 
-      - name: Verify and Checkout Deploy Branch 🔄
-        run: |
-          git fetch origin
-          echo "📂 Verifying 'develop_deploy' branch..."
-          if git rev-parse --verify origin/develop_deploy; then
-            git checkout develop_deploy
-            echo "✅ Branch checked out successfully!"
-          else
-            echo "❌ Branch 'develop_deploy' not found. Please verify the branch name."
-            exit 1
-          fi
+  #     - name: Deleting the sdm directory for fresh build ⚙️
+  #       run: |
+  #         echo "🔄 Deleting 'sdm' directory for fresh build..."
+  #         pwd
+  #         cd
+  #         rm -rf .m2/repository/com/sap/cds
+  #         echo "✅ 'sdm' directory deleted!"
 
-      - name: Deleting the sdm directory for fresh build ⚙️
-        run: |
-          echo "🔄 Deleting 'sdm' directory for fresh build..."
-          pwd
-          cd
-          rm -rf .m2/repository/com/sap/cds
-          echo "✅ 'sdm' directory deleted!"
+  #     - name: Set REPOSITORY_ID 🔍
+  #       id: set_repository_id
+  #       run: |
+  #         echo "🔄 Setting Repository ID..."
+  #         if [ "${{ github.event.inputs.cf_space }}" = "developcap" ]; then
+  #           echo "Using REPOSITORY_ID from secrets"
+  #           echo "::set-output name=repository_id::${{ secrets.REPOSITORY_ID }}"
+  #         else
+  #           if [ -z "${{ github.event.inputs.repository_id }}" ]; then
+  #             echo "❌ REPOSITORY_ID must be provided for non-developcap spaces"
+  #             exit 1
+  #           else
+  #             echo "Using provided REPOSITORY_ID"
+  #             echo "::set-output name=repository_id::${{ github.event.inputs.repository_id }}"
+  #           fi
+  #         fi
 
-      - name: Set REPOSITORY_ID 🔍
-        id: set_repository_id
-        run: |
-          echo "🔄 Setting Repository ID..."
-          if [ "${{ github.event.inputs.cf_space }}" = "developcap" ]; then
-            echo "Using REPOSITORY_ID from secrets"
-            echo "::set-output name=repository_id::${{ secrets.REPOSITORY_ID }}"
-          else
-            if [ -z "${{ github.event.inputs.repository_id }}" ]; then
-              echo "❌ REPOSITORY_ID must be provided for non-developcap spaces"
-              exit 1
-            else
-              echo "Using provided REPOSITORY_ID"
-              echo "::set-output name=repository_id::${{ github.event.inputs.repository_id }}"
-            fi
-          fi
+  #     - name: Configure Maven for GitHub Packages 📦
+  #       run: |
+  #         echo "🔧 Configuring Maven for GitHub Packages..."
+  #         mkdir -p ~/.m2
+  #         cat > ~/.m2/settings.xml <<EOF
+  #         <settings>
+  #           <servers>
+  #             <server>
+  #               <id>github-snapshot</id>
+  #               <username>${{ github.actor }}</username>
+  #               <password>${{ secrets.GITHUB_TOKEN }}</password>
+  #             </server>
+  #           </servers>
+  #         </settings>
+  #         EOF
+  #         echo "✅ Maven configuration complete!"
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Configure Maven for GitHub Packages 📦
-        run: |
-          echo "🔧 Configuring Maven for GitHub Packages..."
-          mkdir -p ~/.m2
-          cat > ~/.m2/settings.xml <<EOF
-          <settings>
-            <servers>
-              <server>
-                <id>github-snapshot</id>
-                <username>${{ github.actor }}</username>
-                <password>${{ secrets.GITHUB_TOKEN }}</password>
-              </server>
-            </servers>
-          </settings>
-          EOF
-          echo "✅ Maven configuration complete!"
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #     - name: Prepare and Deploy to Cloud Foundry ☁️
+  #       run: |
+  #         echo "🔄 Preparing to deploy..."
+  #         echo "Current Branch: 📂"
+  #         git branch
+  #         pwd
+  #         cd /home/runner/work/sdm/sdm/cap-notebook/demoapp
 
-      - name: Prepare and Deploy to Cloud Foundry ☁️
-        run: |
-          echo "🔄 Preparing to deploy..."
-          echo "Current Branch: 📂"
-          git branch
-          pwd
-          cd /home/runner/work/sdm/sdm/cap-notebook/demoapp
+  #         cd app
+  #         echo "🔄 Removing node_modules for fresh install..."
+  #         rm -rf node_modules package-lock.json
 
-          cd app
-          echo "🔄 Removing node_modules for fresh install..."
-          rm -rf node_modules package-lock.json
+  #         echo "🔧 Installing npm dependencies..."
+  #         npm i
 
-          echo "🔧 Installing npm dependencies..."
-          npm i
+  #         cd ..
 
-          cd ..
+  #         echo "🔧 Configuring mta.yaml..."
+  #         sed -i 's|__REPOSITORY_ID__|'${{ steps.set_repository_id.outputs.repository_id }}'|g' ./mta.yaml
 
-          echo "🔧 Configuring mta.yaml..."
-          sed -i 's|__REPOSITORY_ID__|'${{ steps.set_repository_id.outputs.repository_id }}'|g' ./mta.yaml
+  #         echo "📦 Downloading and setting up MBT..."
+  #         wget -P /tmp https://github.com/SAP/cloud-mta-build-tool/releases/download/v1.2.28/cloud-mta-build-tool_1.2.28_Linux_amd64.tar.gz
+  #         tar -xvzf /tmp/cloud-mta-build-tool_1.2.28_Linux_amd64.tar.gz
+  #         sudo mv mbt /usr/local/bin/
 
-          echo "📦 Downloading and setting up MBT..."
-          wget -P /tmp https://github.com/SAP/cloud-mta-build-tool/releases/download/v1.2.28/cloud-mta-build-tool_1.2.28_Linux_amd64.tar.gz
-          tar -xvzf /tmp/cloud-mta-build-tool_1.2.28_Linux_amd64.tar.gz
-          sudo mv mbt /usr/local/bin/
+  #         echo "🚀 Building with MBT..."
+  #         mbt build
+  #         echo "✅ Build completed!"
 
-          echo "🚀 Building with MBT..."
-          mbt build
-          echo "✅ Build completed!"
+  #         echo "🔧 Installing Cloud Foundry CLI..."
+  #         wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo tee /etc/apt/trusted.gpg.d/cloudfoundry.asc
+  #         echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
+  #         sudo apt update
+  #         sudo apt install cf-cli
 
-          echo "🔧 Installing Cloud Foundry CLI..."
-          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo tee /etc/apt/trusted.gpg.d/cloudfoundry.asc
-          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
-          sudo apt update
-          sudo apt install cf-cli
+  #         cf install-plugin multiapps -f
 
-          cf install-plugin multiapps -f
+  #         echo "🔑 Logging into Cloud Foundry..."
+  #         cf login -a ${{ secrets.CF_API }} -u ${{ secrets.CF_USER }} -p ${{ secrets.CF_PASSWORD }} -o ${{ secrets.CF_ORG }} -s ${{ github.event.inputs.cf_space }}
+  #         echo "✅ Logged in successfully!"
 
-          echo "🔑 Logging into Cloud Foundry..."
-          cf login -a ${{ secrets.CF_API }} -u ${{ secrets.CF_USER }} -p ${{ secrets.CF_PASSWORD }} -o ${{ secrets.CF_ORG }} -s ${{ github.event.inputs.cf_space }}
-          echo "✅ Logged in successfully!"
-
-          echo "🚀 Running cf deploy..."
-          cf deploy mta_archives/demoappjava_1.0.0.mtar -f
-          echo "✅ Deployment complete!"
+  #         echo "🚀 Running cf deploy..."
+  #         cf deploy mta_archives/demoappjava_1.0.0.mtar -f
+  #         echo "✅ Deployment complete!"
