Update deploy_and_Integration_test.yml

diff --git a/.github/workflows/deploy_and_Integration_test.yml b/.github/workflows/deploy_and_Integration_test.yml
--- a/.github/workflows/deploy_and_Integration_test.yml
+++ b/.github/workflows/deploy_and_Integration_test.yml
@@ -1,107 +1,199 @@
-name: Deploy and Integration Test
+name: Build, Snapshot Deploy, Deploy and Test
+
+env:
+  JAVA_VERSION: '17'
+  MAVEN_VERSION: '3.6.3'
 
 on:
-  #pull_request:
-    #types: [closed]
   push:
-    branches:
-      - wait_time1
+    branches: [ "wait_time" ]
+  # pull_request:
+  #   types: [closed]
+  #   branches:
+  #     - develop
   workflow_dispatch:
 
 permissions:
   pull-requests: read
-  packages: read  # Added permission to read packages
+  packages: write  # Required for updating packages 
 
 jobs:
-  deploy:
-    #if: github.event.pull_request.merged == true
+  build:
+    name: Build
     runs-on: ubuntu-latest
+    if: ${{ github.event_name == 'push' || github.event.pull_request.merged == true }}
+    strategy:
+      matrix:
+        java-version: [ 17 ]
 
     steps:
-      - name: Wait for 5 minutes # to get new snapshot deploy to artifactory
-        run: sleep 300
-        
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Build
+        uses: ./.github/actions/build
+        with:
+          java-version: ${{ matrix.java-version }}
+          maven-version: ${{ env.MAVEN_VERSION }}
+
+  update-version:
+    name: Update version
+    runs-on: ubuntu-latest
+    needs: [ build ]
+    if: ${{ github.event_name == 'push' || github.event.pull_request.merged == true }}
+    permissions:
+      contents: read
+      packages: write
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Set up Java ${{ env.JAVA_VERSION }}
+        uses: actions/setup-java@v4
+        with:
+          java-version: ${{ env.JAVA_VERSION }}
+          distribution: sapmachine
+          cache: maven
+
+      - name: Set up Maven ${{ env.MAVEN_VERSION }}
+        uses: stCarolas/setup-maven@v5
+        with:
+          maven-version: ${{ env.MAVEN_VERSION }}
+
+      - name: Get Revision
+        id: get-revision
+        run: |
+          current_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
+          echo "Current version: $current_version"
+          echo "REVISION=$current_version" >> $GITHUB_ENV
+        shell: bash
+
+      - name: Check and Update Version
+        if: github.ref == 'refs/heads/develop'
+        id: check-and-update-version
+        run: |
+          current_version=${{ env.REVISION }}
+          # Check if the version already contains '-SNAPSHOT'
+          if [[ $current_version != *-SNAPSHOT ]]; then
+            echo "Current version does not contain -SNAPSHOT, updating version..."
+            # Split version into major, minor, and patch parts
+            IFS='.' read -r major minor patch <<< "$(echo $current_version | tr '-' '.')"
+            # Increment the patch number
+            new_patch=$((patch + 1))
+            # Form the new version
+            new_version="${major}.${minor}.${new_patch}-SNAPSHOT"
+            # Update the <revision> property in pom.xml
+            sed -i "s|<revision>.*</revision>|<revision>${new_version}</revision>|" pom.xml
+            echo "Updated version to $new_version"
+            # Commit the version change
+            git config --local user.name "github-actions"
+            git config --local user.email "github-actions@github.com"
+            git add pom.xml
+            git commit -m "Increment version to ${new_version}"
+            git push origin HEAD:develop
+          else
+            echo "Current version already contains -SNAPSHOT, no update needed."
+          fi
+          # Export the updated or original version
+          updated_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
+          echo "UPDATED_VERSION=$updated_version" >> $GITHUB_ENV
+        shell: bash
+
+      - name: Print Updated Version
+        run: |
+          echo "Updated version: ${{ env.UPDATED_VERSION }}"
+        shell: bash
+
+      # - name: Deploy snapshot
+      #   if: ${{ endsWith(env.UPDATED_VERSION, '-SNAPSHOT') }}
+      #   run: |
+      #     mvn -B -ntp -fae -Dmaven.install.skip=true -Dmaven.test.skip=true -DdeployAtEnd=true -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/cap-java/sdm deploy
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
+      #   shell: bash
+
+  deploy:
+    name: Deploy and Integration Test
+    runs-on: ubuntu-latest
+    needs: [update-version]
+    if: ${{ github.event.pull_request.merged == true }}
+    
+    steps:
+      - name: Wait for 5 minutes
+        run: sleep 30
+
       - name: Checkout repository
         uses: actions/checkout@v2
         with:
           ref: develop
 
-      - name: Set up Java 17
-        uses: actions/setup-java@v3
-        with:
-          java-version: 17
-          distribution: 'temurin'
+      # - name: Set up Java 17
+      #   uses: actions/setup-java@v3
+      #   with:
+      #     java-version: 17
+      #     distribution: 'temurin'
 
-      - name: Verify and Checkout Deploy Branch
-        run: |
-          git fetch origin
-          if git rev-parse --verify origin/develop_deploy; then
-            git checkout develop_deploy
-          else
-            echo "Branch 'develop_deploy' not found. Please verify the branch name."
-            exit 1
-          fi
-
-      - name: Deleting the sdm directory for fresh build
-        run: |
-          pwd
-          cd
-          rm -rf .m2/repository/com/sap/cds
-
-      - name: Configure Maven for GitHub Packages
-        run: |
-          mkdir -p ~/.m2
-          cat > ~/.m2/settings.xml <<EOF
-          <settings>
-            <servers>
-              <server>
-                <id>github-snapshot</id>
-                <username>${{ github.actor }}</username>
-                <password>${{ secrets.GITHUB_TOKEN }}</password>
-              </server>
-            </servers>
-          </settings>
-          EOF
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      # - name: Consume GitHub Packages (com.sap.cds.sdm-root and com.sap.cds.sdm)
+      # - name: Verify and Checkout Deploy Branch
       #   run: |
-      #     mvn dependency:get -Dartifact=com.sap.cds:sdm-root:LATEST -DrepoUrl=https://maven.pkg.github.com/cap-java/sdm
-      #     mvn dependency:get -Dartifact=com.sap.cds:sdm:LATEST -DrepoUrl=https://maven.pkg.github.com/cap-java/sdm
+      #     git fetch origin
+      #     if git rev-parse --verify origin/develop_deploy; then
+      #       git checkout develop_deploy
+      #     else
+      #       echo "Branch 'develop_deploy' not found. Please verify the branch name."
+      #       exit 1
+      #     fi
 
-      - name: Prepare and Deploy to Cloud Foundry
-        run: |
-          echo "Current Branch......"
-          git branch
-          pwd
-          cd /home/runner/work/sdm/sdm/cap-notebook/demoapp
-          
-          # Replace placeholder with actual REPOSITORY_ID value
-          sed -i 's|__REPOSITORY_ID__|'${{ steps.set_repository_id.outputs.repository_id }}'|g' ./mta.yaml
-          
-          wget -P /tmp https://github.com/SAP/cloud-mta-build-tool/releases/download/v1.2.28/cloud-mta-build-tool_1.2.28_Linux_amd64.tar.gz
-          tar -xvzf /tmp/cloud-mta-build-tool_1.2.28_Linux_amd64.tar.gz
-          sudo mv mbt /usr/local/bin/
+      # - name: Deleting the sdm directory for fresh build
+      #   run: |
+      #     pwd
+      #     cd
+      #     rm -rf .m2/repository/com/sap/cds
 
-          mbt build
-          
-          # Install cf & login 
-          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key \
-          | sudo tee /etc/apt/trusted.gpg.d/cloudfoundry.asc
-          echo "deb https://packages.cloudfoundry.org/debian stable main" \
-          | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
-          sudo apt update
-          sudo apt install cf-cli
-          
-          # Install cf CLI plugin
-          cf install-plugin multiapps -f
+      # - name: Configure Maven for GitHub Packages
+      #   run: |
+      #     mkdir -p ~/.m2
+      #     cat > ~/.m2/settings.xml <<EOF
+      #     <settings>
+      #       <servers>
+      #         <server>
+      #           <id>github-snapshot</id>
+      #           <username>${{ github.actor }}</username>
+      #           <password>${{ secrets.GITHUB_TOKEN }}</password>
+      #         </server>
+      #       </servers>
+      #     </settings>
+      #     EOF
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-          # Login to Cloud Foundry again to ensure session is active
-          cf login -a ${{ secrets.CF_API }} -u ${{ secrets.CF_USER }} -p ${{ secrets.CF_PASSWORD }} -o ${{ secrets.CF_ORG }} -s ${{ secrets.CF_SPACE }}
-
-          # Deploy the application
-          echo "Running cf deploy"
-          cf deploy mta_archives/demoappjava_1.0.0.mtar -f
+      # - name: Prepare and Deploy to Cloud Foundry
+      #   run: |
+      #     echo "Current Branch......"
+      #     git branch
+      #     pwd
+      #     cd /home/runner/work/sdm/sdm/cap-notebook/demoapp
+          
+      #     # Replace placeholder with actual REPOSITORY_ID value
+      #     sed -i 's|__REPOSITORY_ID__|'${{ steps.set_repository_id.outputs.repository_id }}'|g' ./mta.yaml
+          
+      #     wget -P /tmp https://github.com/SAP/cloud-mta-build-tool/releases/download/v1.2.28/cloud-mta-build-tool_1.2.28_Linux_amd64.tar.gz
+      #     tar -xvzf /tmp/cloud-mta-build-tool_1.2.28_Linux_amd64.tar.gz
+      #     sudo mv mbt /usr/local/bin/
+      #     mbt build
+          
+      #     # Install cf & login 
+      #     wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key \
+      #     | sudo tee /etc/apt/trusted.gpg.d/cloudfoundry.asc
+      #     echo "deb https://packages.cloudfoundry.org/debian stable main" \
+      #     | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
+      #     sudo apt update
+      #     sudo apt install cf-cli
+          
+      #     # Install cf CLI plugin
+      #     cf install-plugin multiapps -f
+      #     cf login -a ${{ secrets.CF_API }} -u ${{ secrets.CF_USER }} -p ${{ secrets.CF_PASSWORD }} -o ${{ secrets.CF_ORG }} -s ${{ secrets.CF_SPACE }}
+      #     cf deploy mta_archives/demoappjava_1.0.0.mtar -f
 
   integration-test:
     needs: deploy
@@ -196,7 +288,3 @@ jobs:
           EOL
           # Run Maven integration tests
           mvn clean verify -P integration-tests -DskipUnitTests || { echo "Maven tests failed"; exit 1; }
-    
-      
-
-      
