Update integration_test.yml

diff --git a/.github/workflows/integration_test.yml b/.github/workflows/integration_test.yml
--- a/.github/workflows/integration_test.yml
+++ b/.github/workflows/integration_test.yml
@@ -25,6 +25,9 @@ jobs:
 
       - name: Run integration tests
         run: |
+          set -e  # Enable error checking
+
+          # Gather secrets and other values
           appUrl="${{ secrets.CF_ORG }}-${{ secrets.CF_SPACE }}-demoappjava-srv.cfapps.eu12.hana.ondemand.com"
           authUrl="${{ secrets.CAPAUTH_URL }}"
           clientID="${{ secrets.CAPSDM_CLIENT_ID }}"
@@ -35,8 +38,7 @@ jobs:
           # Function to partially mask sensitive information
           mask() {
             local value="$1"
-            local mask_length=5
-            echo "${value:0:3}$(printf '*%.0s' $(seq ${mask_length}))"
+            echo "${value:0:3}*****"
           }
 
           # Print masked versions of the credentials for debugging
@@ -50,13 +52,26 @@ jobs:
           # Properties file path
           PROPERTIES_FILE="sdm/src/test/resources/credentials.properties"
 
-          # Modify properties file with jq
-          jq --arg appUrl "$appUrl" --arg authUrl "$authUrl" --arg clientID "$clientID" --arg clientSecret "$clientSecret" --arg username "$username" --arg password "$password" \
-          '.appUrl = $appUrl | .authUrl = $authUrl | .clientID = $clientID | .clientSecret = $clientSecret | .username = $username | .password = $password' "$PROPERTIES_FILE" > "temp.properties" \
-          && mv "temp.properties" "$PROPERTIES_FILE" || { echo "Failed to update properties file"; exit 1; }
-          
+          # Create a new JSON file
+          jq -n \
+            --arg appUrl "$appUrl" \
+            --arg authUrl "$authUrl" \
+            --arg clientID "$clientID" \
+            --arg clientSecret "$clientSecret" \
+            --arg username "$username" \
+            --arg password "$password" \
+            '{
+              "appUrl": $appUrl,
+              "authUrl": $authUrl,
+              "clientID": $clientID,
+              "clientSecret": $clientSecret,
+              "username": $username,
+              "password": $password
+            }' > "$PROPERTIES_FILE" \
+            || { echo "Failed to update properties file"; exit 1; }  # Exit if jq command fails
+
           # Print confirmation of file modification without actual values
           echo "Successfully updated $PROPERTIES_FILE"
-          
+
           # Run Maven integration tests
           mvn clean verify -P integration-tests -DskipUnitTests || { echo "Maven tests failed"; exit 1; }
