Update multi tenancy_Integration.yml

diff --git a/.github/workflows/multi tenancy_Integration.yml b/.github/workflows/multi tenancy_Integration.yml
--- a/.github/workflows/multi tenancy_Integration.yml
+++ b/.github/workflows/multi tenancy_Integration.yml
@@ -173,15 +173,15 @@ jobs:
           clientIDMT=$clientIDMT
           clientSecretMT=$clientSecretMT
           username=$username
-          password="*******"
+          password=$password
           noSDMRoleUsername=$noSDMRoleUsername
           noSDMRoleUserPassword=$noSDMRoleUserPassword
           EOL
 
-          # Display properties file with already masked sensitive information
-          echo -e "\033[34m📜 Properties File:\033[0m"
-          cat "$PROPERTIES_FILE"
+          # # Display properties file with already masked sensitive information
+          # echo -e "\033[34m📜 Properties File:\033[0m"
+          # cat "$PROPERTIES_FILE"
 
           echo -e "\033[34m🧪 Running Maven tests for Multi Tenancy...\033[0m"
-          # mvn clean verify -P integration-tests -DtokenFlow=namedUser -DtenancyModel=multi -Dtenant=TENANT1 -DskipUnitTests > /dev/null || { echo -e "\033[31m❌ Maven tests failed for Named User Flow (Multi Tenancy, Tenant 1)\033[0m"; exit 1; }
+          mvn clean verify -P integration-tests -DtokenFlow=namedUser -DtenancyModel=multi -Dtenant=TENANT1 -DskipUnitTests > /dev/null || { echo -e "\033[31m❌ Maven tests failed for Named User Flow (Multi Tenancy, Tenant 1)\033[0m"; exit 1; }
           echo -e "\033[32m✔️ Integration tests completed successfully!\033[0m"
