Update multi tenancy_Integration.yml

diff --git a/.github/workflows/multi tenancy_Integration.yml b/.github/workflows/multi tenancy_Integration.yml
--- a/.github/workflows/multi tenancy_Integration.yml
+++ b/.github/workflows/multi tenancy_Integration.yml
@@ -2,7 +2,7 @@ name: Multi Tenancy Integration Test
 
 on:
   push:
-    branches:
+   branches:
       - multiTenancy_IntegrationTest
   workflow_dispatch:
     inputs:
@@ -22,7 +22,7 @@ jobs:
 
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v3
+        uses: actions/checkout@v2
         with:
           ref: ${{ github.event.inputs.branch_name }}
 
@@ -34,13 +34,10 @@ jobs:
 
       - name: Install Cloud Foundry CLI and jq
         run: |
-          echo -e "\033[36m🔧 Installing Cloud Foundry CLI and jq...\033[0m"
           wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
           echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
           sudo apt-get update
-          sudo apt-get install -y cf8-cli jq
-          echo -e "\033[32m✔️ Installation complete!\033[0m"
-
+          sudo apt-get install cf8-cli jq
       - name: Determine Cloud Foundry Space
         id: determine_space
         run: |
@@ -49,102 +46,76 @@ jobs:
           else
             space="${{ github.event.inputs.cf_space }}"
           fi
-          echo -e "\033[34m🌐 Space determined: \033[1m$space\033[22m\033[0m"
+          echo "Space determined: $space"
           echo "::set-output name=space::$space"
-
       - name: Login to Cloud Foundry
         run: |
-          echo -e "\033[36m🔑 Logging in to Cloud Foundry...\033[0m"
+          echo "Space Name: ${{ steps.determine_space.outputs.space }}"
           cf login -a ${{ secrets.CF_API }} \
             -u ${{ secrets.CF_USER }} \
             -p ${{ secrets.CF_PASSWORD }} \
             -o ${{ secrets.CF_ORG }} \
-            -s ${{ secrets.CF_SPACE }} > /dev/null
-          echo -e "\033[32m✔️ Login successful!\033[0m"
-
-      - name: Fetch Client Details for Single Tenant
+            -s ${{ secrets.CF_SPACE }}
+            # -s ${{ steps.determine_space.outputs.space }}
+      - name: Fetch and Escape Client Details for single tenant
         id: fetch_credentials
         run: |
-          echo -e "\033[36m🚀 Fetching Client Details for Single Tenant...\033[0m"
           service_instance_guid=$(cf service demoappjava-public-uaa --guid)
           if [ -z "$service_instance_guid" ]; then
-            echo -e "\033[31m❌ Error: Unable to retrieve service instance GUID\033[0m"
-            exit 1
+            echo "Error: Unable to retrieve service instance GUID"; exit 1;
           fi
           
           bindings_response=$(cf curl "/v3/service_credential_bindings?service_instance_guids=${service_instance_guid}")
           binding_guid=$(echo $bindings_response | jq -r '.resources[0].guid')
           if [ -z "$binding_guid" ]; then
-            echo -e "\033[31m❌ Error: Unable to retrieve binding GUID\033[0m"
-            exit 1
+            echo "Error: Unable to retrieve binding GUID"; exit 1;
           fi
           
           binding_details=$(cf curl "/v3/service_credential_bindings/${binding_guid}/details")
-
-          # Fetch and store the actual client credentials
+          
           clientSecret=$(echo "$binding_details" | jq -r '.credentials.clientsecret')
           if [ -z "$clientSecret" ] || [ "$clientSecret" == "null" ]; then
-            echo -e "\033[31m❌ Error: clientSecret is not set or is null\033[0m"
-            exit 1
+            echo "Error: clientSecret is not set or is null"; exit 1;
           fi
-
+          escapedClientSecret=$(echo "$clientSecret" | sed 's/\$/\\$/g')
+          
           clientID=$(echo "$binding_details" | jq -r '.credentials.clientid')
           if [ -z "$clientID" ] || [ "$clientID" == "null" ]; then
-            echo -e "\033[31m❌ Error: clientID is not set or is null\033[0m"
-            exit 1
+            echo "Error: clientID is not set or is null"; exit 1;
           fi
-
-          # Create masked versions for logging
-          maskedClientSecret="****${clientSecret: -4}"
-          maskedClientID="****${clientID: -4}"
-
-          echo "::set-output name=CLIENT_SECRET::$clientSecret"
+          
+          echo "::set-output name=CLIENT_SECRET::$escapedClientSecret"
           echo "::set-output name=CLIENT_ID::$clientID"
-          echo -e "\033[32m✔️ Client Details fetched successfully!\033[0m"
-          echo -e "\033[34m⚠️ ClientID: $maskedClientID\033[0m"
-          echo -e "\033[34m⚠️ ClientSecret: $maskedClientSecret\033[0m"
-
-      - name: Fetch Client Details for Multi Tenant
+      - name: Fetch and Escape Client Details for multi tenant
         id: fetch_credentials_mt
         run: |
-            echo -e "\033[36m🚀 Fetching Client Details for Multi Tenant...\033[0m"
             service_instance_guid=$(cf service bookshop-mt-uaa --guid)
             if [ -z "$service_instance_guid" ]; then
-              echo -e "\033[31m❌ Error: Unable to retrieve service instance GUID\033[0m"
-              exit 1
+              echo "Error: Unable to retrieve service instance GUID"; exit 1;
             fi
             
             bindings_response=$(cf curl "/v3/service_credential_bindings?service_instance_guids=${service_instance_guid}")
             binding_guid=$(echo $bindings_response | jq -r '.resources[0].guid')
             if [ -z "$binding_guid" ]; then
-              echo -e "\033[31m❌ Error: Unable to retrieve binding GUID\033[0m"
-              exit 1
+              echo "Error: Unable to retrieve binding GUID"; exit 1;
             fi
             
             binding_details=$(cf curl "/v3/service_credential_bindings/${binding_guid}/details")
-
-            # Fetch and store the actual client credentials
+            
             clientSecret_mt=$(echo "$binding_details" | jq -r '.credentials.clientsecret')
             if [ -z "$clientSecret_mt" ] || [ "$clientSecret_mt" == "null" ]; then
-              echo -e "\033[31m❌ Error: clientSecret_mt is not set or is null\033[0m"
-              exit 1
+              echo "Error: clientSecret_mt is not set or is null"; exit 1;
             fi
-
+            escapedClientSecret_mt=$(echo "$clientSecret_mt" | sed 's/\$/\\$/g')
+            
             clientID_mt=$(echo "$binding_details" | jq -r '.credentials.clientid')
             if [ -z "$clientID_mt" ] || [ "$clientID_mt" == "null" ]; then
-              echo -e "\033[31m❌ Error: clientID_mt is not set or is null\033[0m"
-              exit 1
+              echo "Error: clientID_mt is not set or is null"; exit 1;
             fi
-
-            # Create masked versions for logging
-            maskedClientSecretMT="****${clientSecret_mt: -4}"
-            maskedClientIDMT="****${clientID_mt: -4}"
-
-            echo "::set-output name=CLIENT_SECRET_MT::$clientSecret_mt"
+            
+            echo "::set-output name=CLIENT_SECRET_MT::$escapedClientSecret_mt"
             echo "::set-output name=CLIENT_ID_MT::$clientID_mt"
-            echo -e "\033[32m✔️ Multi Tenant Client Details fetched successfully!\033[0m"
-            echo -e "\033[34m⚠️ ClientID_MT: $maskedClientIDMT\033[0m"
-            echo -e "\033[34m⚠️ ClientSecret_MT: $maskedClientSecretMT\033[0m"
+  
 
       - name: Run integration tests
         env:
@@ -153,51 +124,61 @@ jobs:
           CLIENT_SECRET_MT: ${{ steps.fetch_credentials_mt.outputs.CLIENT_SECRET_MT }}
           CLIENT_ID_MT: ${{ steps.fetch_credentials_mt.outputs.CLIENT_ID_MT }}
         run: |
-          echo -e "\033[36m🧪 Running Integration Tests...\033[0m"
           set -e
-
+  
           PROPERTIES_FILE="sdm/src/test/resources/credentials.properties"
-          appUrl="${{ secrets.CF_ORG }}-${{ secrets.CF_SPACE }}-demoappjava-srv.cfapps.eu12.hana.ondemand.com"
-          appUrlMT="${{ secrets.CF_ORG }}-${{ secrets.CF_SPACE }}-bookshop-mt-srv.cfapps.eu12.hana.ondemand.com"
-          authUrl="${{ secrets.CAPAUTH_URL }}"
-          authUrlMT1="${{ secrets.AUTHURLMT1 }}"
-          authUrlMT2="${{ secrets.AUTHURLMT2 }}"
-          username="${{ secrets.CF_USER }}"
-          password="${{ secrets.CF_PASSWORD }}"
-          noSDMRoleUsername="${{ secrets.NOSDMROLEUSERNAME }}"
-          noSDMRoleUserPassword="${{ secrets.NOSDMROLEUSERPASSWORD }}"
-
-          clientID="${{ env.CLIENT_ID }}"
-          clientSecret="${{ env.CLIENT_SECRET }}"
-          clientIDMT="${{ env.CLIENT_ID_MT }}"
-          clientSecretMT="${{ env.CLIENT_SECRET_MT }}"
-
-          # Write sensitive info to properties file for operational use, display masked versions only
-          maskedClientID="****${clientID: -4}"
-          maskedClientSecret="****${clientSecret: -4}"
-          maskedClientIDMT="****${clientIDMT: -4}"
-          maskedClientSecretMT="****${clientSecretMT: -4}"
-
+          
+          declare -A variables=( 
+            ["appUrl"]="${{ secrets.CF_ORG }}-${{ secrets.CF_SPACE }}-demoappjava-srv.cfapps.eu12.hana.ondemand.com"
+            ["appUrlMT"]="${{ secrets.CF_ORG }}-${{ secrets.CF_SPACE }}-bookshop-mt-srv.cfapps.eu12.hana.ondemand.com"
+            ["authUrl"]="${{ secrets.CAPAUTH_URL }}"
+            ["authUrlMT1"]="${{ secrets.AUTHURLMT1 }}"
+            ["authUrlMT2"]="${{ secrets.AUTHURLMT2 }}"
+            ["clientID"]="${{ env.CLIENT_ID }}"
+            ["clientSecret"]="${{ env.CLIENT_SECRET }}"
+            ["clientIDMT"]="${{ env.CLIENT_ID_MT }}"
+            ["clientSecretMT"]="${{ env.CLIENT_SECRET_MT }}"
+            ["username"]="${{ secrets.CF_USER }}"
+            ["password"]="${{ secrets.CF_PASSWORD }}"
+            ["noSDMRoleUsername"]="${{ secrets.NOSDMROLEUSERNAME }}"
+            ["noSDMRoleUserPassword"]="${{ secrets.NOSDMROLEUSERPASSWORD }}"
+          )
+  
+          mask() {
+            local value="$1"
+            if [ ${#value} -gt 6 ]; then
+              echo "${value:0:3}*****${value: -3}"
+            else
+              echo "${value:0:2}*****"
+            fi
+          }
+  
+          # Mask all secrets in logs
+          for key in "${!variables[@]}"; do
+            echo "::add-mask::${variables[$key]}"
+            if [ -z "${variables[$key]}" ]; then
+              echo "Error: $key is not set"
+              exit 1
+            fi
+          done
+  
+          # Write to the properties file
           cat > "$PROPERTIES_FILE" <<EOL
-          appUrl=$appUrl
-          appUrlMT=$appUrlMT
-          authUrl=$authUrl
-          authUrlMT1=$authUrlMT1
-          authUrlMT2=$authUrlMT2
-          clientID=$maskedClientID
-          clientSecret=$maskedClientSecret
-          clientIDMT=$maskedClientIDMT
-          clientSecretMT=$maskedClientSecretMT
-          username=$username
-          password=$password
-          noSDMRoleUsername=$noSDMRoleUsername
-          noSDMRoleUserPassword=$noSDMRoleUserPassword
+          appUrl=${variables["appUrl"]}
+          appUrlMT=${variables["appUrlMT"]}
+          authUrl=${variables["authUrl"]}
+          authUrlMT1=${variables["authUrlMT1"]}
+          authUrlMT2=${variables["authUrlMT2"]}
+          clientID=$(mask "${variables["clientID"]}")
+          clientSecret=$(mask "${variables["clientSecret"]}")
+          clientIDMT=$(mask "${variables["clientIDMT"]}")
+          clientSecretMT=$(mask "${variables["clientSecretMT"]}")
+          username=$(mask "${variables["username"]}")
+          password=$(mask "${variables["password"]}")
+          noSDMRoleUsername=$(mask "${variables["noSDMRoleUsername"]}")
+          noSDMRoleUserPassword=$(mask "${variables["noSDMRoleUserPassword"]}")
           EOL
-
-          # Display properties file with masked sensitive information
-          echo -e "\033[34m📜 Properties File:\033[0m"
-          cat "$PROPERTIES_FILE"
-
-          echo -e "\033[34m🧪 Running Maven tests for Multi Tenancy...\033[0m"
-          mvn clean verify -P integration-tests -DtokenFlow=namedUser -DtenancyModel=multi -Dtenant=TENANT1 -DskipUnitTests > /dev/null || { echo -e "\033[31m❌ Maven tests failed for Named User Flow (Multi Tenancy, Tenant 1)\033[0m"; exit 1; }
-          echo -e "\033[32m✔️ Integration tests completed successfully!\033[0m"
+          # mvn clean verify -P integration-tests -DtokenFlow=namedUser -DtenancyModel=multi -Dtenant=TENANT1 -DskipUnitTests
+          # mvn clean verify -P integration-tests -DtokenFlow=technicalUser -DtenancyModel=multi -Dtenant=TENANT1 -DskipUnitTests 
+          # mvn clean verify -P integration-tests -DtokenFlow=namedUser -DtenancyModel=multi -Dtenant=TENANT2 -DskipUnitTests
+          # mvn clean verify -P integration-tests -DtokenFlow=technicalUser -DtenancyModel=multi -Dtenant=TENANT2 -DskipUnitTests
