Update multi tenancy_Integration.yml

diff --git a/.github/workflows/multi tenancy_Integration.yml b/.github/workflows/multi tenancy_Integration.yml
--- a/.github/workflows/multi tenancy_Integration.yml
+++ b/.github/workflows/multi tenancy_Integration.yml
@@ -57,38 +57,38 @@ jobs:
             -u ${{ secrets.CF_USER }} \
             -p ${{ secrets.CF_PASSWORD }} \
             -o ${{ secrets.CF_ORG }} \
-            -s developcap
+            -s ${{ secrets.CF_SPACE }}
             # -s ${{ steps.determine_space.outputs.space }}
 
-      # - name: Fetch and Escape Client Details for single tenant
-      #   id: fetch_credentials
-      #   run: |
-      #     service_instance_guid=$(cf service demoappjava-public-uaa --guid)
-      #     if [ -z "$service_instance_guid" ]; then
-      #       echo "Error: Unable to retrieve service instance GUID"; exit 1;
-      #     fi
+      - name: Fetch and Escape Client Details for single tenant
+        id: fetch_credentials
+        run: |
+          service_instance_guid=$(cf service demoappjava-public-uaa --guid)
+          if [ -z "$service_instance_guid" ]; then
+            echo "Error: Unable to retrieve service instance GUID"; exit 1;
+          fi
           
-      #     bindings_response=$(cf curl "/v3/service_credential_bindings?service_instance_guids=${service_instance_guid}")
-      #     binding_guid=$(echo $bindings_response | jq -r '.resources[0].guid')
-      #     if [ -z "$binding_guid" ]; then
-      #       echo "Error: Unable to retrieve binding GUID"; exit 1;
-      #     fi
+          bindings_response=$(cf curl "/v3/service_credential_bindings?service_instance_guids=${service_instance_guid}")
+          binding_guid=$(echo $bindings_response | jq -r '.resources[0].guid')
+          if [ -z "$binding_guid" ]; then
+            echo "Error: Unable to retrieve binding GUID"; exit 1;
+          fi
           
-      #     binding_details=$(cf curl "/v3/service_credential_bindings/${binding_guid}/details")
+          binding_details=$(cf curl "/v3/service_credential_bindings/${binding_guid}/details")
           
-      #     clientSecret=$(echo "$binding_details" | jq -r '.credentials.clientsecret')
-      #     if [ -z "$clientSecret" ] || [ "$clientSecret" == "null" ]; then
-      #       echo "Error: clientSecret is not set or is null"; exit 1;
-      #     fi
-      #     escapedClientSecret=$(echo "$clientSecret" | sed 's/\$/\\$/g')
+          clientSecret=$(echo "$binding_details" | jq -r '.credentials.clientsecret')
+          if [ -z "$clientSecret" ] || [ "$clientSecret" == "null" ]; then
+            echo "Error: clientSecret is not set or is null"; exit 1;
+          fi
+          escapedClientSecret=$(echo "$clientSecret" | sed 's/\$/\\$/g')
           
-      #     clientID=$(echo "$binding_details" | jq -r '.credentials.clientid')
-      #     if [ -z "$clientID" ] || [ "$clientID" == "null" ]; then
-      #       echo "Error: clientID is not set or is null"; exit 1;
-      #     fi
+          clientID=$(echo "$binding_details" | jq -r '.credentials.clientid')
+          if [ -z "$clientID" ] || [ "$clientID" == "null" ]; then
+            echo "Error: clientID is not set or is null"; exit 1;
+          fi
           
-      #     echo "::set-output name=CLIENT_SECRET::$escapedClientSecret"
-      #     echo "::set-output name=CLIENT_ID::$clientID"
+          echo "::set-output name=CLIENT_SECRET::$escapedClientSecret"
+          echo "::set-output name=CLIENT_ID::$clientID"
 
       - name: Fetch and Escape Client Details for multi tenant
         id: fetch_credentials_mt
@@ -123,33 +123,33 @@ jobs:
 
       - name: Run integration tests
         env:
-          # CLIENT_SECRET: ${{ steps.fetch_credentials.outputs.CLIENT_SECRET }}
-          # CLIENT_ID: ${{ steps.fetch_credentials.outputs.CLIENT_ID }}
+          CLIENT_SECRET: ${{ steps.fetch_credentials.outputs.CLIENT_SECRET }}
+          CLIENT_ID: ${{ steps.fetch_credentials.outputs.CLIENT_ID }}
           CLIENT_SECRET_MT: ${{ steps.fetch_credentials_mt.outputs.CLIENT_SECRET_MT }}
           CLIENT_ID_MT: ${{ steps.fetch_credentials_mt.outputs.CLIENT_ID_MT }}
         run: |
           set -e
           PROPERTIES_FILE="sdm/src/test/resources/credentials.properties"
-          # appUrl="${{ secrets.CF_ORG }}-${{ secrets.CF_SPACE }}-demoappjava-srv.cfapps.eu12.hana.ondemand.com"
+          appUrl="${{ secrets.CF_ORG }}-${{ secrets.CF_SPACE }}-demoappjava-srv.cfapps.eu12.hana.ondemand.com"
           appUrlMT="${{ secrets.CF_ORG }}-${{ secrets.CF_SPACE }}-bookshop-mt-srv.cfapps.eu12.hana.ondemand.com"
-          # authUrl="${{ secrets.CAPAUTH_URL }}"
+          authUrl="${{ secrets.CAPAUTH_URL }}"
           authUrlMT1="${{ secrets.AUTHURLMT1 }}"
           authUrlMT2="${{ secrets.AUTHURLMT2 }}" 
-          # clientID="${{ env.CLIENT_ID }}"
-          # clientSecret="${{ env.CLIENT_SECRET }}"
+          clientID="${{ env.CLIENT_ID }}"
+          clientSecret="${{ env.CLIENT_SECRET }}"
           clientIDMT="${{ env.CLIENT_ID_MT }}"
           clientSecretMT="${{ env.CLIENT_SECRET_MT }}"
           username="${{ secrets.CF_USER }}"
           password="${{ secrets.CF_PASSWORD }}"
           noSDMRoleUsername="${{ secrets.NOSDMROLEUSERNAME }}"
           noSDMRoleUserPassword="${{ secrets.NOSDMROLEUSERPASSWORD }}"
-          # if [ -z "$appUrl" ]; then echo "Error: appUrl is not set"; exit 1; fi
+          if [ -z "$appUrl" ]; then echo "Error: appUrl is not set"; exit 1; fi
           if [ -z "$appUrlMT" ]; then echo "Error: appUrlMT is not set"; exit 1; fi
-          # if [ -z "$authUrl" ]; then echo "Error: authUrl is not set"; exit 1; fi
+          if [ -z "$authUrl" ]; then echo "Error: authUrl is not set"; exit 1; fi
           if [ -z "$authUrlMT1" ]; then echo "Error: authUrlMT1 is not set"; exit 1; fi
           if [ -z "$authUrlMT2" ]; then echo "Error: authUrlMT2 is not set"; exit 1; fi
-          # if [ -z "$clientID" ]; then echo "Error: clientID is not set"; exit 1; fi
-          # if [ -z "$clientSecret" ]; then echo "Error: clientSecret is not set"; exit 1; fi
+          if [ -z "$clientID" ]; then echo "Error: clientID is not set"; exit 1; fi
+          if [ -z "$clientSecret" ]; then echo "Error: clientSecret is not set"; exit 1; fi
           if [ -z "$clientIDMT" ]; then echo "Error: clientIDMT is not set"; exit 1; fi
           if [ -z "$clientSecretMT" ]; then echo "Error: clientSecretMT is not set"; exit 1; fi
           if [ -z "$username" ]; then echo "Error: username is not set"; exit 1; fi
@@ -167,13 +167,13 @@ jobs:
           }
 
           cat > "$PROPERTIES_FILE" <<EOL
-          # appUrl=$appUrl
+          appUrl=$appUrl
           appUrlMT=$appUrlMT
-          # authUrl=$authUrl
+          authUrl=$authUrl
           authUrlMT1=$authUrlMT1
           authUrlMT2=$authUrlMT2
-          # clientID=$clientID
-          # clientSecret=$clientSecret
+          clientID=$clientID
+          clientSecret=$clientSecret
           clientIDMT=$clientIDMT
           clientSecretMT=$clientSecretMT
           username=$username
