Update multi tenancy_Integration.yml

diff --git a/.github/workflows/multi tenancy_Integration.yml b/.github/workflows/multi tenancy_Integration.yml
--- a/.github/workflows/multi tenancy_Integration.yml
+++ b/.github/workflows/multi tenancy_Integration.yml
@@ -1,6 +1,9 @@
 name: Multi Tenancy Integration Test
 
 on:
+  push:
+    branches:
+      - multiTenancy_IntegrationTest
   workflow_dispatch:
     inputs:
       cf_space:
@@ -19,7 +22,7 @@ jobs:
 
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
         with:
           ref: ${{ github.event.inputs.branch_name }}
 
@@ -31,10 +34,12 @@ jobs:
 
       - name: Install Cloud Foundry CLI and jq
         run: |
+          echo -e "\033[36mInstalling Cloud Foundry CLI and jq...\033[0m"
           wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
           echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
           sudo apt-get update
-          sudo apt-get install cf8-cli jq
+          sudo apt-get install -y cf8-cli jq
+          echo -e "\033[32mInstallation complete!\033[0m"
 
       - name: Determine Cloud Foundry Space
         id: determine_space
@@ -44,78 +49,90 @@ jobs:
           else
             space="${{ github.event.inputs.cf_space }}"
           fi
-          echo "Space determined: $space"
+          echo -e "\033[34mSpace determined: \033[1m$space\033[22m\033[0m"
           echo "::set-output name=space::$space"
 
       - name: Login to Cloud Foundry
         run: |
-          echo "Space Name: ${{ steps.determine_space.outputs.space }}"
+          echo -e "\033[36mLogging in to Cloud Foundry...\033[0m"
           cf login -a ${{ secrets.CF_API }} \
             -u ${{ secrets.CF_USER }} \
             -p ${{ secrets.CF_PASSWORD }} \
             -o ${{ secrets.CF_ORG }} \
             -s ${{ steps.determine_space.outputs.space }}
+          echo -e "\033[32mLogin successful!\033[0m"
 
       - name: Fetch and Escape Client Details for single tenant
         id: fetch_credentials
         run: |
+          echo -e "\033[36mFetching Client Details for Single Tenant...\033[0m"
           service_instance_guid=$(cf service demoappjava-public-uaa --guid)
           if [ -z "$service_instance_guid" ]; then
-            echo "Error: Unable to retrieve service instance GUID"; exit 1;
+            echo -e "\033[31mError: Unable to retrieve service instance GUID\033[0m"
+            exit 1
           fi
           
           bindings_response=$(cf curl "/v3/service_credential_bindings?service_instance_guids=${service_instance_guid}")
           binding_guid=$(echo $bindings_response | jq -r '.resources[0].guid')
           if [ -z "$binding_guid" ]; then
-            echo "Error: Unable to retrieve binding GUID"; exit 1;
+            echo -e "\033[31mError: Unable to retrieve binding GUID\033[0m"
+            exit 1
           fi
           
           binding_details=$(cf curl "/v3/service_credential_bindings/${binding_guid}/details")
           
           clientSecret=$(echo "$binding_details" | jq -r '.credentials.clientsecret')
           if [ -z "$clientSecret" ] || [ "$clientSecret" == "null" ]; then
-            echo "Error: clientSecret is not set or is null"; exit 1;
+            echo -e "\033[31mError: clientSecret is not set or is null\033[0m"
+            exit 1
           fi
           escapedClientSecret=$(echo "$clientSecret" | sed 's/\$/\\$/g')
           
           clientID=$(echo "$binding_details" | jq -r '.credentials.clientid')
           if [ -z "$clientID" ] || [ "$clientID" == "null" ]; then
-            echo "Error: clientID is not set or is null"; exit 1;
+            echo -e "\033[31mError: clientID is not set or is null\033[0m"
+            exit 1
           fi
           
           echo "::set-output name=CLIENT_SECRET::$escapedClientSecret"
           echo "::set-output name=CLIENT_ID::$clientID"
+          echo -e "\033[32mClient Details fetched successfully!\033[0m"
 
       - name: Fetch and Escape Client Details for multi tenant
         id: fetch_credentials_mt
         run: |
+            echo -e "\033[36mFetching Client Details for Multi Tenant...\033[0m"
             service_instance_guid=$(cf service bookshop-mt-uaa --guid)
             if [ -z "$service_instance_guid" ]; then
-              echo "Error: Unable to retrieve service instance GUID"; exit 1;
+              echo -e "\033[31mError: Unable to retrieve service instance GUID\033[0m"
+              exit 1
             fi
             
             bindings_response=$(cf curl "/v3/service_credential_bindings?service_instance_guids=${service_instance_guid}")
             binding_guid=$(echo $bindings_response | jq -r '.resources[0].guid')
             if [ -z "$binding_guid" ]; then
-              echo "Error: Unable to retrieve binding GUID"; exit 1;
+              echo -e "\033[31mError: Unable to retrieve binding GUID\033[0m"
+              exit 1
             fi
             
             binding_details=$(cf curl "/v3/service_credential_bindings/${binding_guid}/details")
             
             clientSecret_mt=$(echo "$binding_details" | jq -r '.credentials.clientsecret')
             if [ -z "$clientSecret_mt" ] || [ "$clientSecret_mt" == "null" ]; then
-              echo "Error: clientSecret_mt is not set or is null"; exit 1;
+              echo -e "\033[31mError: clientSecret_mt is not set or is null\033[0m"
+              exit 1
             fi
             escapedClientSecret_mt=$(echo "$clientSecret_mt" | sed 's/\$/\\$/g')
             
             clientID_mt=$(echo "$binding_details" | jq -r '.credentials.clientid')
             if [ -z "$clientID_mt" ] || [ "$clientID_mt" == "null" ]; then
-              echo "Error: clientID_mt is not set or is null"; exit 1;
+              echo -e "\033[31mError: clientID_mt is not set or is null\033[0m"
+              exit 1
             fi
             
             echo "::set-output name=CLIENT_SECRET_MT::$escapedClientSecret_mt"
             echo "::set-output name=CLIENT_ID_MT::$clientID_mt"
-  
+            echo -e "\033[32mMulti Tenant Client Details fetched successfully!\033[0m"
 
       - name: Run integration tests
         env:
@@ -124,6 +141,7 @@ jobs:
           CLIENT_SECRET_MT: ${{ steps.fetch_credentials_mt.outputs.CLIENT_SECRET_MT }}
           CLIENT_ID_MT: ${{ steps.fetch_credentials_mt.outputs.CLIENT_ID_MT }}
         run: |
+          echo -e "\033[36mRunning Integration Tests...\033[0m"
           set -e
           PROPERTIES_FILE="sdm/src/test/resources/credentials.properties"
           appUrl="${{ secrets.CF_ORG }}-${{ steps.determine_space.outputs.space }}-demoappjava-srv.cfapps.eu12.hana.ondemand.com"
@@ -139,28 +157,14 @@ jobs:
           password="${{ secrets.CF_PASSWORD }}"
           noSDMRoleUsername="${{ secrets.NOSDMROLEUSERNAME }}"
           noSDMRoleUserPassword="${{ secrets.NOSDMROLEUSERPASSWORD }}"
-          if [ -z "$appUrl" ]; then echo "Error: appUrl is not set"; exit 1; fi
-          if [ -z "$appUrlMT" ]; then echo "Error: appUrlMT is not set"; exit 1; fi
-          if [ -z "$authUrl" ]; then echo "Error: authUrl is not set"; exit 1; fi
-          if [ -z "$authUrlMT1" ]; then echo "Error: authUrlMT1 is not set"; exit 1; fi
-          if [ -z "$authUrlMT2" ]; then echo "Error: authUrlMT2 is not set"; exit 1; fi
-          if [ -z "$clientID" ]; then echo "Error: clientID is not set"; exit 1; fi
-          if [ -z "$clientSecret" ]; then echo "Error: clientSecret is not set"; exit 1; fi
-          if [ -z "$clientIDMT" ]; then echo "Error: clientIDMT is not set"; exit 1; fi
-          if [ -z "$clientSecretMT" ]; then echo "Error: clientSecretMT is not set"; exit 1; fi
-          if [ -z "$username" ]; then echo "Error: username is not set"; exit 1; fi
-          if [ -z "$password" ]; then echo "Error: password is not set"; exit 1; fi
-          if [ -z "$noSDMRoleUsername" ]; then echo "Error: noSDMRoleUsername is not set"; exit 1; fi
-          if [ -z "$noSDMRoleUserPassword" ]; then echo "Error: noSDMRoleUserPassword is not set"; exit 1; fi
-
-          mask() {
-            local value="$1"
-            if [ ${#value} -gt 6 ]; then
-              echo "${value:0:3}*****${value: -3}"
-            else
-              echo "${value:0:2}*****"
+          
+          # Check for missing variables
+          for var in appUrl appUrlMT authUrl authUrlMT1 authUrlMT2 clientID clientSecret clientIDMT clientSecretMT username password noSDMRoleUsername noSDMRoleUserPassword; do
+            if [ -z "${!var}" ]; then
+              echo -e "\033[31mError: ${var} is not set\033[0m"
+              exit 1
             fi
-          }
+          done
 
           cat > "$PROPERTIES_FILE" <<EOL
           appUrl=$appUrl
@@ -178,10 +182,16 @@ jobs:
           noSDMRoleUserPassword=$noSDMRoleUserPassword
           EOL
 
+          # Display properties file
+          echo -e "\033[34mProperties File:\033[0m"
+          cat "$PROPERTIES_FILE"
+          
           # Run Maven integration tests
-          # mvn clean verify -P integration-tests -DtokenFlow=namedUser -DtenancyModel=single -DskipUnitTests || { echo "Maven tests failed for Technical User Flow"; exit 1; }
-          # mvn clean verify -P integration-tests -DtokenFlow=technicalUser -DtenancyModel=single -DskipUnitTests || { echo "Maven tests failed for Named User Flow"; exit 1; }
-          mvn clean verify -P integration-tests -DtokenFlow=namedUser -DtenancyModel=multi -Dtenant=TENANT1 -DskipUnitTests
-          mvn clean verify -P integration-tests -DtokenFlow=technicalUser -DtenancyModel=multi -Dtenant=TENANT1 -DskipUnitTests 
-          mvn clean verify -P integration-tests -DtokenFlow=namedUser -DtenancyModel=multi -Dtenant=TENANT2 -DskipUnitTests
-          mvn clean verify -P integration-tests -DtokenFlow=technicalUser -DtenancyModel=multi -Dtenant=TENANT2 -DskipUnitTests
+
+          echo -e "\033[34mRunning Maven tests for Multi Tenancy...\033[0m"
+          mvn clean verify -P integration-tests -DtokenFlow=namedUser -DtenancyModel=multi -Dtenant=TENANT1 -DskipUnitTests || { echo -e "\033[31mMaven tests failed for Named User Flow (Multi Tenancy, Tenant 1)\033[0m"; exit 1; }
+          # mvn clean verify -P integration-tests -DtokenFlow=technicalUser -DtenancyModel=multi -Dtenant=TENANT1 -DskipUnitTests || { echo -e "\033[31mMaven tests failed for Technical User Flow (Multi Tenancy, Tenant 1)\033[0m"; exit 1; }
+          # mvn clean verify -P integration-tests -DtokenFlow=namedUser -DtenancyModel=multi -Dtenant=TENANT2 -DskipUnitTests || { echo -e "\033[31mMaven tests failed for Named User Flow (Multi Tenancy, Tenant 2)\033[0m"; exit 1; }
+          # mvn clean verify -P integration-tests -DtokenFlow=technicalUser -DtenancyModel=multi -Dtenant=TENANT2 -DskipUnitTests || { echo -e "\033[31mMaven tests failed for Technical User Flow (Multi Tenancy, Tenant 2)\033[0m"; exit 1; }
+
+          echo -e "\033[32mIntegration tests completed successfully!\033[0m"
